graphql.playground.enabled: true

spring:
  mail:
    host: email-smtp.eu-west-3.amazonaws.com
    port: 587

prizy:
  server:
    url: https://api.prizy.io

  storage:
    endpoint: fra1.digitaloceanspaces.com
    server-url: https://api.prizy.io

  security.jwt:
    key-id: production
    issuer: prizy-production
    audience: prizy-public-api
    algorithm: RS256
