graphql.playground.enabled: true

spring:
  mail:
    host: email-smtp.eu-west-3.amazonaws.com
    port: 587

prizy:
  server:
    url: https://api.stg.prizy.io

  storage:
    endpoint: fra1.digitaloceanspaces.com
    server-url: https://api.stg.prizy.io

  security.jwt:
    key-id: staging
    issuer: prizy-staging
    audience: prizy-public-api
    algorithm: RS256

logging.level:
  io.prizy.graphql.logging.GraphQLWebLogger: DEBUG
