graphql.playground.enabled: true

spring:
  mail:
    host: email-smtp.eu-west-3.amazonaws.com
    port: 587
  boot.admin.client:
    url: https://spring-boot-admin-rdhrb.ondigitalocean.app
    instance:
      name: public-api-staging
      service-url: https://api.stg.prizy.io
  elasticsearch:
    uris: https://elastic.prizy.io:443
    username: elastic

prizy:
  logging:
    log-to-elastic-search: true
    index-name: prizy.logs.staging

  server:
    url: https://api.stg.prizy.io

  storage:
    endpoint: fra1.digitaloceanspaces.com
    server-url: https://api.stg.prizy.io

  security.jwt:
    key-id: staging
    issuer: prizy-staging
    audience: prizy-public-api
    algorithm: RS256
