graphql.playground.enabled: true

spring.boot.admin.client:
  url: https://spring-boot-admin-rdhrb.ondigitalocean.app
  instance.name: public-api-production

prizy:
  storage:
    endpoint: fra1.digitaloceanspaces.com
    server-url: https://api.prizy.io

  security.jwt:
    key-id: production
    issuer: prizy-production
    audience: prizy-public-api
    algorithm: RS256
