version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: prizy-web
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:RELEASE.2022-04-30T22-23-53Z
    command: server --console-address ":9001" /data/minio/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
  smtp:
    image: namshi/smtp
    ports:
      - "25:25"
  app:
    image: public-api:1.0.4-SNAPSHOT
    depends_on:
      - db
      - minio
      - smtp
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/prizy-web

volumes:
  db-data:
  minio-data: