version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=prizy-web
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    ports:
      - "8081:8080"
  minio:
    image: quay.io/minio/minio:RELEASE.2022-04-30T22-23-53Z
    command: server --console-address ":9001" /data/minio/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data

#  app:
#    image: public-api
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/prizy-web
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=mysecretpassword

volumes:
  minio-data: