name: Promote Pipeline

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'type'
        default: 'Patch'
        required: true

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Prepare gradle wrapper
        run: chmod +x gradlew

      - name: Prepare promote task
        run: |
          git config --global user.email "ci@prizy.io"
          git config --global user.name "CI Bot"
          [[ ${{ github.event.inputs.type }} = 'Patch' ]] && TASK="release" || TASK="release${{ github.event.inputs.type }}Version"
          echo "TASK=$TASK" >> $GITHUB_ENV

      - name: Promote version
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: ${{ env.TASK }}
